[package]
name = "rusted-tetris"
version = "0.1.0"
authors = ["Lyova Potyomkin <lyova.potyomkin@gmail.com>"]
edition = "2018"

[dependencies]
rand = { version = "0.7", features = ["small_rng", "alloc"] }
termion = "1.5"

[profile.release]
lto = true
panic = 'abort'
